# Copyright (c) 2020-2023 SECOM CO., LTD. All Rights reserved.
# SPDX-License-Identifier: BSD-2-Clause

name: Docker Image CI for libcsuit with OpenSSL

on:
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build-ossl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Build the Docker image
      run: |
        docker build -t libcsuit_ossl -f ossl.Dockerfile .
        docker run -t libcsuit_ossl
